name: Node.js CI/CD

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests (if you have tests)
        run: npm test

      - name: Lint code (if you have linting)
        run: npm run lint

      - name: Start server (if needed for tests)
        run: npm start & sleep 5

      - name: Deploy to production (replace with your deployment steps)
        run: |
          # Example deployment steps:
          # - Install pm2 globally (if using pm2 for process management)
          # - Stop the currently running app (if applicable)
          # - Start the app using pm2
          # - Or any other deployment steps you have

      - name: Post-deployment cleanup
        run: |
          # Cleanup steps if needed

      - name: Notify on Slack (optional)
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Deployment successful!"

