export { Category, type ICategory } from "./category.model"
export { Skill, type ISkill } from "./skill.model"
export { Project, type IProject } from "./project.model"
export { Experience, type IExperience } from "./experience.model"
export { Education, type IEducation } from "./education.model"
export { Profile, type IProfile, type ISocials, type IStatItem } from "./profile.model"
